INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (1, 'Munich University', 'Munich');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (2, 'Leiden University', 'Leiden');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (3, 'Amsterdam University', 'Amsterdam');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (4, 'École Polytechnique', 'Paris');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (5, 'École municipale de physique et de chimie industrielles (Municipal School of Industrial Physics and Chemistry)', 'Paris');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (6, 'Royal Institution of Great Britain', 'London');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (7, 'Kiel University', 'Kiel');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (8, 'University of Cambridge', 'Cambridge');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (9, 'University of Chicago', 'Chicago, IL');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (10, 'Sorbonne University', 'Paris');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (11, 'Marconi Wireless Telegraph Co. Ltd.', 'London');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (12, 'Strasbourg University', 'Strasbourg');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (13, 'Würzburg University', 'Würzburg');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (14, 'Swedish Gas-Accumulator Co.', 'Lidingö-Stockholm');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (15, 'Frankfurt-on-the-Main University', 'Frankfurt-on-the-Main');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (16, 'University College', 'London');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (17, 'Victoria University', 'Manchester');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (18, 'Edinburgh University', 'Edinburgh');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (19, 'Berlin University', 'Berlin');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (20, 'Greifswald University', 'Greifswald');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (21, 'Bureau International des Poids et Mesures (International Bureau of Weights and Measures)', 'Sèvres');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (22, 'Kaiser-Wilhelm-Institut (now Max-Planck-Institut) für Physik', 'Berlin');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (23, 'Copenhagen University', 'Copenhagen');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (24, 'California Institute of Technology (Caltech)', 'Pasadena, CA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (25, 'Uppsala University', 'Uppsala');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (26, 'Goettingen University', 'Göttingen');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (27, 'Halle University', 'Halle');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (28, 'London University', 'London');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (29, 'Sorbonne University, Institut Henri Poincaré', 'Paris');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (30, 'Calcutta University', 'Calcutta');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (31, 'Leipzig University', 'Leipzig');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (32, 'Liverpool University', 'Liverpool');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (33, 'Innsbruck University', 'Innsbruck');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (34, 'Bell Telephone Laboratories', 'New York, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (35, 'Rome University', 'Rome');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (36, 'University of California', 'Berkeley, CA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (37, 'Carnegie Institute of Technology', 'Pittsburgh, PA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (38, 'Columbia University', 'New York, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (39, 'Princeton University', 'Princeton, NJ');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (40, 'Harvard University', 'Cambridge, MA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (41, 'Department of Scientific and Industrial Research', 'London');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (42, 'Kyoto Imperial University', 'Kyoto');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (43, 'Bristol University', 'Bristol');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (44, 'Atomic Energy Research Establishment', 'Harwell, Berkshire');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (45, 'Trinity College', 'Dublin');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (46, 'Stanford University', 'Stanford, CA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (47, 'Groningen University', 'Groningen');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (48, 'University of Heidelberg', 'Heidelberg');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (49, 'Semiconductor Laboratory of Beckman Instruments, Inc.', 'Mountain View, CA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (50, 'University of Illinois', 'Urbana, IL');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (51, 'Institute for Advanced Study', 'Princeton, NJ');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (52, 'P.N. Lebedev Physical Institute', 'Moscow');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (53, 'University of Moscow', 'Moscow');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (54, 'Technical University', 'Munich');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (55, 'Academy of Sciences', 'Moscow');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (56, 'Massachusetts Institute of Technology (MIT)', 'Cambridge, MA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (57, 'Tokyo University of Education', 'Tokyo');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (58, 'École Normale Supérieure', 'Paris');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (59, 'Cornell University', 'Ithaca, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (60, 'Royal Institute of Technology', 'Stockholm');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (61, 'University of Grenoble', 'Grenoble');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (62, 'Imperial College', 'London');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (63, 'Brown University', 'Providence, RI');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (64, 'University of Pennsylvania', 'Philadelphia, PA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (65, 'IBM Thomas J. Watson Research Center', 'Yorktown Heights, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (66, 'General Electric Company', 'Schenectady, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (67, 'Niels Bohr Institute', 'Copenhagen');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (68, 'Nordita', 'Copenhagen');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (69, 'Stanford Linear Accelerator Center', 'Stanford, CA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (70, 'Bell Laboratories', 'Holmdel, NJ');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (71, 'Harvard University, Lyman Laboratory', 'Cambridge, MA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (72, 'International Centre for Theoretical Physics', 'Trieste');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (73, 'CERN', 'Geneva');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (74, 'Max-Planck-Institut für Festkörperforschung', 'Stuttgart');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (75, 'Fritz-Haber-Institut der Max-Planck-Gesellschaft', 'Berlin');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (76, 'IBM Zurich Research Laboratory', 'Rüschlikon');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (77, 'Fermi National Accelerator Laboratory', 'Batavia, IL');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (78, 'Digital Pathways, Inc.', 'Mountain View, CA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (79, 'University of Washington', 'Seattle, WA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (80, 'University of Bonn', 'Bonn');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (81, 'Collège de France', 'Paris');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (82, 'École Supérieure de Physique et Chimie', 'Paris');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (83, 'McMaster University', 'Hamilton, Ontario');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (84, 'National Institute of Standards and Technology', 'Gaithersburg, MD');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (85, 'Utrecht University', 'Utrecht');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (86, 'Stockholm University', 'Stockholm');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (87, 'Landwirtschaftliche Hochschule (Agricultural College)', 'Berlin');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (88, 'Nancy University', 'Nancy');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (89, 'Toulouse University', 'Toulouse');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (90, 'University of Zurich', 'Zurich');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (91, 'Kaiser-Wilhelm-Institut (now Fritz-Haber-Institut) für physikalische Chemie und Electrochemie', 'Berlin-Dahlem');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (92, 'University of Oxford', 'Oxford');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (93, 'Graz University', 'Graz');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (94, 'Technische Hochschule (Institute of Technology)', 'Munich');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (95, 'Institut du Radium', 'Paris');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (96, 'Birmingham University', 'Birmingham');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (97, 'Kaiser-Wilhelm-Institut (now Max-Planck Institut) für Medizinische Forschung', 'Heidelberg');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (98, 'Kaiser-Wilhelm-Institut (now Max-Planck-Institut) für Biochemie', 'Berlin-Dahlem');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (99, 'Eidgenössische Technische Hochschule (Swiss Federal Institute of Technology)', 'Zurich');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (100, 'Kaiser-Wilhelm-Institut (now Max-Planck Institut) für Chemie', 'Berlin-Dahlem');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (101, 'University of Helsinki', 'Helsinki');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (102, 'Rockefeller Institute for Medical Research', 'Princeton, NJ');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (103, 'Cologne University', 'Cologne');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (104, 'National Institute for Medical Research', 'London');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (105, 'Rowett Research Institute', 'Bucksburn (Scotland)');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (106, 'University of Freiburg', 'Breisgau');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (107, 'Institute for Chemical Physics of the Academy of Sciences of the USSR', 'Moscow');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (108, 'Polarographic Institute of the Czechoslovak Academy of Science', 'Prague');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (109, 'MRC Laboratory of Molecular Biology', 'Cambridge');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (110, 'Max-Planck-Institut für Kohlenforschung (Max-Planck-Institute for Carbon Research)', 'Mülheim/Ruhr');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (111, 'Institute of Technology', 'Milan');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (112, 'University of Oxford, Royal Society', 'Oxford');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (113, 'Max-Planck-Institut für Physikalische Chemie', 'Göttingen');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (114, 'Institute of Physical Chemistry', 'Cambridge');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (115, 'Yale University', 'New Haven, CT');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (116, 'University of Oslo', 'Oslo');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (117, 'Institute for Biochemical Research', 'Buenos Aires');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (118, 'National Research Council of Canada', 'Ottawa');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (119, 'National Institutes of Health', 'Bethesda, MD');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (120, 'Rockefeller University', 'New York, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (121, 'University of Sussex', 'Brighton');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (122, 'Université Libre de Bruxelles', 'Brussels');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (123, 'Glynn Research Laboratories', 'Bodmin');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (124, 'Purdue University', 'West Lafayette, IN');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (125, 'Harvard University, Biological Laboratories', 'Cambridge, MA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (126, 'Kyoto University', 'Kyoto');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (127, 'The Medical Foundation of Buffalo', 'Buffalo, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (128, 'US Naval Research Laboratory', 'Washington, DC');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (129, 'University of Toronto', 'Toronto');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (130, 'Université Louis Pasteur', 'Strasbourg');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (131, 'Du Pont', 'Wilmington, DE');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (132, 'University of Texas Southwestern Medical Center at Dallas', 'Dallas, TX');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (133, 'Max-Planck-Institut für Biochemie', 'Martinsried');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (134, 'Max-Planck-Institut für Biophysik', 'Frankfurt-on-the-Main');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (135, 'University of Colorado', 'Boulder, CO');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (136, 'University of British Columbia', 'Vancouver');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (137, 'University of Southern California', 'Los Angeles, CA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (138, 'Max-Planck-Institut für Chemie', 'Mainz');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (139, 'Rice University', 'Houston, TX');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (140, 'Aarhus University', 'Aarhus');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (141, 'Northwestern University', 'Evanston, IL');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (142, 'Marburg University', 'Marburg');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (143, 'Finsen Medical Light Institute', 'Copenhagen');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (144, 'Military Medical Academy', 'St. Petersburg');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (145, 'Institute for Infectious Diseases', 'Berlin');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (146, 'Pavia University', 'Pavia');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (147, 'Madrid University', 'Madrid');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (148, 'Institut Pasteur', 'Paris');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (149, 'Berne University', 'Berne');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (150, 'Vienna University', 'Vienna');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (151, 'Brussels University', 'Brussels');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (152, 'Kaiser-Wilhelm-Institut (now Max-Planck-Institut) für Biologie', 'Berlin-Dahlem');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (153, 'University of Rochester', 'Rochester, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (154, 'University of Freiburg im Breisgau', 'Breisgau');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (155, 'Szeged University', 'Szeged');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (156, 'Ghent University', 'Ghent');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (157, 'Munster University', 'Munster');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (158, 'Polytechnic Institute', 'Copenhagen');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (159, 'Saint Louis University', 'St. Louis, MO');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (160, 'Washington University', 'St. Louis, MO');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (161, 'Indiana University', 'Bloomington, IN');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (162, 'Instituto de Biologia y Medicina Experimental (Institute for Biology and Experimental Medicine)', 'Buenos Aires');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (163, 'Laboratorium der Farben-Fabriken J.R. Geigy A.G. (Laboratory of the J.R. Geigy Dye-Factory Co.)', 'Basel');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (164, 'University of Lisbon', 'Lisbon');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (165, 'Mayo Clinic', 'Rochester, MN');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (166, 'Basel University', 'Basel');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (167, 'Laboratories of the Division of Medicine and Public Health, Rockefeller Foundation', 'New York, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (168, 'Rutgers University', 'New Brunswick, NJ');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (169, 'Sheffield University', 'Sheffield');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (170, 'Harvard Medical School', 'Boston, MA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (171, 'Research Division of Infectious Diseases, Children''s Medical Center', 'Boston, MA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (172, 'Western Reserve University', 'Cleveland, OH');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (173, 'Karolinska Institutet, Nobel Medical Institute', 'Stockholm');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (174, 'Columbia University Division, Cardio-Pulmonary Laboratory, Bellevue Hospital', 'New York, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (175, 'Mainz University', 'Mainz');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (176, 'Istituto Superiore di Sanità (Chief Institute of Public Health)', 'Rome');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (177, 'University of Wisconsin', 'Madison, WI');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (178, 'New York University, College of Medicine', 'New York, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (179, 'Walter and Eliza Hall Institute for Medical Research', 'Melbourne');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (180, 'Australian National University', 'Canberra');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (181, 'Max-Planck-Institut für Zellchemie', 'Munich');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (182, 'University of Chicago, Ben May Laboratory for Cancer Research', 'Chicago, IL');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (183, 'Karolinska Institutet', 'Stockholm');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (184, 'Carnegie Institution of Washington', 'Long Island, New York, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (185, 'Vanderbilt University', 'Nashville, TN');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (186, 'Zoologisches Institut der Universität München', 'Munich');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (187, 'Konrad-Lorenz-Institut der Österreichischen Akademie der Wissen­schaften, Forschungsstelle für Ethologie', 'Altenberg; Grünau im Almtal');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (188, 'Université Catholique de Louvain', 'Louvain');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (189, 'Yale University, School of Medicine', 'New Haven, CT');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (190, 'Imperial Cancer Research Fund Laboratory', 'London');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (191, 'The Institute for Cancer Research', 'Philadelphia, PA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (192, 'The Salk Institute', 'San Diego, CA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (193, 'Veterans Administration Hospital', 'New Orleans, LA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (194, 'Biozentrum der Universität', 'Basel');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (195, 'Johns Hopkins University School of Medicine', 'Baltimore, MD');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (196, 'Tufts University', 'Medford, MA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (197, 'Central Research Laboratories, EMI', 'London');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (198, 'Université de Paris, Laboratoire Immuno-Hématologie', 'Paris');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (199, 'Jackson Laboratory', 'Bar Harbor, ME');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (200, 'The Wellcome Research Laboratories', 'Beckenham');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (201, 'Cold Spring Harbor Laboratory', 'Cold Spring Harbor, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (202, 'Basel Institute for Immunology', 'Basel');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (203, 'Vanderbilt University School of Medicine', 'Nashville, TN');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (204, 'Institute of Cell Biology of the C.N.R.', 'Rome');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (205, 'London University, King''s College Hospital Medical School', 'London');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (206, 'Wellcome Research Laboratories', 'Research Triangle Park, NC');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (207, 'University of California School of Medicine', 'San Francisco, CA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (208, 'Brigham and Women''s Hospital', 'Boston, MA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (209, 'Fred Hutchinson Cancer Research Center', 'Seattle, WA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (210, 'Max-Planck-Institut für Biophysikalische Chemie', 'Göttingen');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (211, 'Max-Planck-Institut für medizinische Forschung', 'Heidelberg');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (212, 'New England Biolabs', 'Beverly, MA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (213, 'Massachusetts Institute of Technology (MIT), Center for Cancer Research', 'Cambridge, MA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (214, 'National Institute of Environmental Health Sciences', 'Research Triangle Park, NC');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (215, 'Max-Planck-Institut für Entwicklungsbiologie', 'Tübingen');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (216, 'St. Jude Children''s Research Hospital', 'Memphis, TN');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (217, 'University of Zurich, Institute of Experimental Immunology', 'Zurich');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (218, 'SUNY Health Science Center', 'Brooklyn, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (219, 'University of Texas Medical School at Houston', 'Houston, TX');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (220, 'The Netherlands School of Economics', 'Rotterdam');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (221, 'All Souls College', 'Oxford');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (222, 'Stockholm School of Economics', 'Stockholm');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (223, 'Carnegie Mellon University', 'Pittsburgh, PA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (224, 'Center for Study of Public Choice', 'Fairfax, VA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (225, 'École Nationale Supérieur des Mines de Paris', 'Paris');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (226, 'City University of New York', 'New York, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (227, 'Rheinische Friedrich-Wilhelms-Universität', 'Bonn');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (228, 'Long Term Capital Management', 'Greenwich, CT');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (229, 'Göteborg University', 'Gothenburg');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (230, 'A.F. Ioffe Physico-Technical Institute', 'St. Petersburg');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (231, 'Texas Instruments', 'Dallas, TX');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (232, 'University of Tsukuba', 'Tokyo');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (233, 'Imperial Cancer Research Fund', 'London');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (234, 'University of Colorado, JILA', 'Boulder, CO');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (235, 'Nagoya University', 'Nagoya');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (236, 'The Scripps Research Institute', 'La Jolla, CA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (237, 'The Molecular Sciences Institute', 'Berkeley, CA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (238, 'The Wellcome Trust Sanger Institute', 'Cambridge');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (239, 'University of Tokyo', 'Tokyo');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (240, 'Associated Universities Inc.', 'Washington, DC');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (241, 'Virginia Commonwealth University', 'Richmond, VA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (242, 'Shimadzu Corp.', 'Kyoto');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (243, 'George Mason University', 'Fairfax, VA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (244, 'University of Nottingham, School of Physics and Astronomy', 'Nottingham');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (245, 'Argonne National Laboratory', 'Argonne, IL');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (246, 'New York University', 'New York, NY');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (247, 'University of California, Kavli Institute for Theoretical Physics', 'Santa Barbara, CA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (248, 'Technion - Israel Institute of Technology', 'Haifa');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (249, 'Arizona State University', 'Tempe, AZ');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (250, 'NHMRC Helicobacter pylori Research Laboratory, QEII Medical Centre', 'Nedlands');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (251, 'Max-Planck-Institut für Quantenoptik', 'Garching');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (252, 'Institut Français du Pétrole', 'Rueil-Malmaison');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (253, 'University of Jerusalem, Center for RationalityHebrew', 'Jerusalem');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (254, 'University of Maryland, Department of Economics and School of Public Policy', 'College Park, MD');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (255, 'Stanford University School of Medicine', 'Stanford, CA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (256, 'University of Massachusetts Medical School', 'Worcester, MA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (257, 'NASA Goddard Space Flight Center', 'Greenbelt, MD');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (258, 'University of Utah', 'Salt Lake City, UT');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (259, 'Cardiff University', 'Cardiff');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (260, 'University of North Carolina', 'Chapel Hill, NC');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (261, 'Universit&eacute; Paris-Sud', 'Orsay');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (262, 'Forschungszentrum J&uuml;lich', 'J&uuml;lich');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (263, 'University of Minnesota', 'Minneapolis, MN');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (264, 'German Cancer Research Center', 'Heidelberg');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (265, 'Regulation of Retroviral Infections Unit, Virology Department, Institut Pasteur', 'Paris');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (266, 'World Foundation for AIDS Research and Prevention', 'Paris');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (267, 'Enrico Fermi Institute, University of Chicago', 'Chicago, IL');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (268, 'High Energy Accelerator Research Organization (KEK)', 'Tsukuba');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (269, 'Kyoto Sangyo University', 'Kyoto');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (270, 'Marine Biological Laboratory (MBL)', 'Woods Hole, MA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (271, 'Standard Telecommunication Laboratories', 'Harlow');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (272, 'Weizmann Institute of Science', 'Rehovot');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (273, 'University of Manchester', 'Manchester');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (274, 'University of Delaware', null);
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (275, 'Hokkaido University', 'Sapporo');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (276, 'London School of Economics and Political Science', 'London');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (277, 'University of Strasbourg', 'Strasbourg');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (278, 'Lawrence Berkeley National Laboratory', 'Berkeley, CA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (279, 'Johns Hopkins University', 'Baltimore, MD');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (280, 'Gurdon Institute', 'Cambridge');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (281, 'Howard Hughes Medical Institute', null);
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (282, 'University of Edinburgh', 'Edinburgh');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (283, 'Université de Strasbourg', 'Strasbourg');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (284, 'Norwegian University of Science and Technology (NTNU)', 'Trondheim');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (285, 'Meijo University', 'Nagoya');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (286, 'Janelia Research Campus, Howard Hughes Medical Institute', 'Ashburn, VA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (287, 'Max Planck Institute for Biophysical Chemistry', 'Göttingen');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (288, 'Toulouse School of Economics (TSE)', 'Toulouse');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (289, 'Drew University', 'Madison, NJ');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (290, 'Kitasato University', 'Tokyo');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (291, 'China Academy of Traditional Chinese Medicine', 'Beijing');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (292, 'Queen''s University', 'Kingston');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (293, 'Francis Crick Institute', 'Hertfordshire');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (294, 'Tokyo Institute of Technology', 'Tokyo');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (295, 'University of Groningen', 'Groningen');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (296, 'University of Maine', 'Maine, ME');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (297, 'Brandeis University', 'Waltham, MA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (298, 'LIGO/VIRGO Collaboration', null);
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (299, 'University of Lausanne', 'Lausanne');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (300, 'Parker Institute for Cancer Immunotherapy', 'San Francisco, CA');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (301, 'University of Waterloo', 'Waterloo');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (302, 'University of Missouri', 'Columbia');
INSERT INTO unknowngenius.Affiliation (idAffiliation, name, address) VALUES (303, 'NYU Stern School of Business', 'New York, NY');