INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (1, 'Germany', 'DE');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (2, 'the Netherlands', 'NL');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (3, 'France', 'FR');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (4, 'Germany (now Poland)', 'PL');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (5, 'United Kingdom', 'GB');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (6, 'Hungary (now Slovakia)', 'SK');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (7, 'Luxembourg', 'LU');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (8, 'Italy', 'IT');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (9, 'Russia', 'RU');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (10, 'Sweden', 'SE');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (11, 'Australia', 'AU');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (12, 'Switzerland', 'CH');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (13, 'Denmark', 'DK');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (14, 'USA', 'US');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (15, 'India', 'IN');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (16, 'Austria', 'AT');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (17, 'Japan', 'JP');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (18, 'Ireland', 'IE');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (19, 'China', 'CN');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (20, 'Russian Empire (now Azerbaijan)', 'AZ');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (21, 'Hungary', 'HU');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (22, 'Norway', 'NO');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (23, 'Pakistan', 'PK');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (24, 'Canada', 'CA');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (25, 'French Algeria (now Algeria)', 'DZ');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (26, 'New Zealand', 'NZ');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (27, 'Russian Empire (now Latvia)', 'LV');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (28, 'Austria-Hungary (now Slovenia)', 'SI');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (29, 'Austria-Hungary (now Croatia)', 'HR');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (30, 'Finland', 'FI');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (31, 'Czechoslovakia (now Czech Republic)', 'CZ');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (32, 'Egypt', 'EG');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (33, 'Bosnia (now Bosnia and Herzegovina)', 'BA');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (34, 'Ukraine', 'UA');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (35, 'Russian Empire (now Lithuania)', 'LT');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (36, 'Taiwan', 'TW');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (37, 'Korea (now South Korea)', 'KR');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (38, 'Mexico', 'MX');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (39, 'Spain', 'ES');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (40, 'Belgium', 'BE');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (41, 'Java, Dutch East Indies (now Indonesia)', 'ID');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (42, 'Argentina', 'AR');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (43, 'Portugal', 'PT');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (44, 'South Africa', 'ZA');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (45, 'Brazil', 'BR');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (46, 'Romania', 'RO');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (47, 'Venezuela', 'VE');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (48, 'NoCountry', 'NN');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (49, 'Southern Rhodesia (now Zimbabwe)', 'ZW');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (50, 'Vietnam', 'VN');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (51, 'USSR (now Belarus)', 'BY');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (52, 'Ottoman Empire (now Republic of Macedonia)', 'MK');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (53, 'Costa Rica', 'CR');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (54, 'Burma (now Myanmar)', 'MM');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (55, 'Guatemala', 'GT');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (56, 'British Mandate of Palestine (now Israel)', 'IL');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (57, 'East Timor', 'TL');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (58, 'Chile', 'CL');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (59, 'Iceland', 'IS');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (60, 'Guadeloupe Island', 'GP');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (61, 'Turkey', 'TR');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (62, 'Crete (now Greece)', 'GR');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (63, 'Bulgaria', 'BG');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (64, 'Colombia', 'CO');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (65, 'Madagascar', 'MG');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (66, 'Nigeria', 'NG');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (67, 'British West Indies (now Saint Lucia)', 'LC');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (68, 'Gold Coast (now Ghana)', 'GH');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (69, 'Persia (now Iran)', 'IR');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (70, 'Kenya', 'KE');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (71, 'British India (now Bangladesh)', 'BD');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (72, 'Peru', 'PE');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (73, 'Cyprus', 'CY');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (74, 'Liberia', 'LR');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (75, 'Yemen', 'YE');
INSERT INTO unknowngenius.Country (idCountry, name, code) VALUES (76, 'Morocco', 'MA');